language: node_js
node_js:
- 8
notifications:
  slack:
    secure: PP7+uGkqJUGxjfZVRs4HxdpV/I2WPq7Mk2BN5M5xhf0rkZUJXU+uTNZRGX/jlNjuYF6kpVzLve4XBEhU1FCyva2Rrj59QdM9hCCH2uhxCHod05gtJmYXr5NwK1R/ovVu1jJRUHhJYoUgty07YynbXdixPocbH2VIOhLWJ192dR/R3l/KFYikFkK6dSzZiAmUjE79n3tXiz5RwKFPIrBrinLr09PhBjUhl61DnB5wBYxwXhG2ylU1d5JlVFNJ10RULYSCyRCBk3dwFpn9DSd+W7jLnwclKQJN3fMjdgFOVms3NYgqhWUeOXC/7z+K7qJuxUtVRYdWOV87UbPbWo1ZoW0JfowfBfOPjm3zBs5CGgI9Kh1EZo33RMb09f24nEOUF2ZhxkVsp2rkERnAzNd7gvFJoX8vjXnVS6B49RGrAO0ofer51Ya5gOkFqVFNNXODG0hvaslaxaBlPh2m+hmI1TfZP+rPYeP//Xlb39Qfvj1NWTxecPdDWH4A72qFVp404/ycEhPyHwbZWHPEaDqnBm+UvIE6ixFl9fQKspVlT0G3WZGN9ZacHSnU0wIkecDrCLlgPHYXNwoObg69+/L+3HC4jT7jnRwikswIQ7rNfAagQFSu7jPSAMcRN68UiqpcyytEYsrqClZhH+Ci/2EhdFJxSLCXp84nRd0SbevWpcs=
